export const siteConfig = {
  name: "MarathiCode",
  tagline: "कोडिंग शिका तुमच्या स्वाभिमानी भाषेत",
  description: "A beginner-friendly programming language featuring native Marathi Devanagari syntax, scoped functions, structured control flow, and real-time execution.",
  url: "https://marathicode.sprouttech.in",
  author: "Deep Shah",
  company: "Sprout Tech",
  companyUrl: "https://www.sprouttech.in",
  github: "https://github.com/deepshah/marathicode",
  version: "1.0.0",
  colors: {
    green: "#43B02A",
    blue: "#0E5A9C",
    ink: "#111111",
    muted: "#555555",
    line: "#E5E7EB",
    paper: "#FAFAFA",
  },
  navLinks: [
    { name: "Overview", href: "/" },
    { name: "Documentation", href: "/docs" },
    // { name: "Playground", href: "/playground" },
    { name: "Examples", href: "/examples" },
  ],
  keywords: [
    { marathi: "चल", english: "VAR", description: "Variable declaration", example: "चल वय = १०" },
    { marathi: "छापा", english: "PRINT", description: "Print statement", example: 'छापा("नमसकार")' },
    { marathi: "जर", english: "IF", description: "If condition", example: "जर अ > १० तर { ... }" },
    { marathi: "तर", english: "THEN", description: "Then block qualifier", example: "जर खरे तर { ... }" },
    { marathi: "नाहीतर", english: "ELSE", description: "Else branch qualifier", example: "नाहीतर { ... }" },
    { marathi: "पर्यंत", english: "WHILE", description: "While loop", example: "पर्यंत x < ५ { ... }" },
    { marathi: "कार्य", english: "FUNCTION", description: "Function definition", example: "कार्य बेरीज(a, b) { ... }" },
    { marathi: "परत", english: "RETURN", description: "Return value", example: "परत a + b" },
    { marathi: "खरे", english: "TRUE", description: "Boolean true literal", example: "चल पास = खरे" },
    { marathi: "खोटे", english: "FALSE", description: "Boolean false literal", example: "चल नापास = खोटे" },
    { marathi: "आणि", english: "AND", description: "Logical AND operator", example: "जर x > ० आणि y > ० तर" },
    { marathi: "किंवा", english: "OR", description: "Logical OR operator", example: "जर x == १ किंवा y == १ तर" },
    { marathi: "नाही", english: "NOT", description: "Logical NOT operator", example: "जर नाही खोटे तर" },
  ]
} as const;
